#!/bin/sh
go get -u github.com/alecthomas/gometalinter
gometalinter --install > /dev/null


gometalinter \
    --vendor \
    --disable-all \
    --enable=vet \
    --enable=vetshadow \
    --enable=golint \
    --enable=ineffassign \
    --enable=goconst \
    --enable=goimports \
    --enable=deadcode \
    --enable=gosimple \
    --enable=errcheck \
    --tests \
    --deadline=60s \
    --exclude=/usr/local/go/src/ \
    --exclude=pkg/artifactory/responses/testdata \
    --exclude=pkg/artifactory/requests/testdata \
    ./artifactory.v54 ./artifactory.v51 ./cmd/... ./pkg/...
